### ISSUE TITLE
Things that don't work in "next"

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/flixel#1471]
Many of these issues are likely the "fault" of OpenFL rather than flixel, but I wanted to make a comprehensive list of everything I've found to be standing in the way of a full transition to openfl-next, so we can tick them off one by one and push forward.

- [x] Music doesn't loop properly in Mode demo: https://github.com/openfl/openfl/issues/595
- [x] Lower framerate in Next than in Legacy: https://github.com/openfl/openfl/issues/596
- [x] Text discrepancies: https://github.com/openfl/openfl/issues/589
- [x] Dial in remaining TextMetrics differences: https://github.com/openfl/openfl/issues/599
- [x] Blurry rendering on half-pixel positions: https://github.com/openfl/openfl/issues/594
- [x] Shared Object: https://github.com/openfl/openfl/issues/593
- [x] Upside-down scaled images in flixel-ui: https://github.com/openfl/openfl/issues/597
- [x] Input text does not work: https://github.com/openfl/openfl/issues/598
- [x] Class cast error in flixel-ui: https://github.com/HaxeFlixel/flixel-ui/issues/99
- [x] BitmapData fillRect / draw discrepancy https://github.com/openfl/openfl/issues/608

New stuff I just found :)
- [x] A few lingering BitmapData text issues with fillRect / draw https://github.com/openfl/openfl/issues/616
- [x] BitmapData.copyPixels() doesn't merge alpha correctly + other issues https://github.com/openfl/openfl/issues/618
- [x] BitmapData flips vertically after a flixel stamp() call: https://github.com/openfl/openfl/issues/623
- [x] BitmapData.copyPixels() merge alpha glitch (different one) https://github.com/openfl/openfl/issues/631
- [x] BitmapData.dispose() inconsistencies/crashing https://github.com/openfl/openfl/issues/632
- [x] BitmapData.merge alpha algorithm https://github.com/openfl/openfl/issues/635

I'll update this as I find more things for us to work on. Feel free to suggest other major TODO issues in the comments and I'll update the checklist. I think Github makes an automated "mini milestone" out of this -- look at any of the linked issues above to see what I mean.

**BOUNTIES**
I'm willing to pay a bounty on each of these; I'd use the BountySource thingy, but since this is a meta-issue and could involve several people, just contact me directly if you solve any of these and we'll work something out.

**Comment by larsiusprime** [comment]
One down!
https://github.com/HaxeFlixel/flixel-ui/issues/99#event-281179431

**Comment by larsiusprime** [comment]
Three down!
And now this one's almost done as soon as the PR is accepted, which will take us to four:
https://github.com/openfl/openfl/issues/599

I'm starting up on this one next:
https://github.com/openfl/openfl/issues/598

**Comment by larsiusprime** [comment]
Audio work starting:
https://github.com/larsiusprime/openfl/tree/audio

**Comment by larsiusprime** [comment]
PR accepted! 4 Down!

https://github.com/openfl/openfl/pull/603

**Comment by larsiusprime** [comment]
Audio work PR's:
https://github.com/openfl/lime/pull/410
https://github.com/openfl/openfl/pull/605

**Comment by larsiusprime** [comment]
PR for upside-down rendering!
https://github.com/openfl/openfl/pull/607

**Comment by larsiusprime** [comment]
Just three more to go! Come on, let's do it!

**Comment by MSGhero** [comment]
I keep checking back, and the list keeps getting longer lol.

**Comment by larsiusprime** [comment]
Haha, just gotta keep on digging and closing em as fast as we can :)

**Comment by sruloart** [comment]
@larsiusprime, can't you also bring down " Blurry rendering on half-pixel positions: openfl/openfl#594 "? it looks kinda solved :)

**Comment by larsiusprime** [comment]
@sruloart Yep!

Now we're just down to input text and shared object before we close this out!

**Comment by Mixerman123** [comment]
This is some really awesome progress guys. Will the next version be out when these issues are resolved? I presume not, but just wondering. Next release looks huge.

**Comment by MSGhero** [comment]
...which means this can be closed too :+1:

**Comment by larsiusprime** [comment]
This is a glorious day.

**Comment by MSGhero** [comment]
Well, if you compare Mode in windows -Dlegacy versus -Dnext, there are some clear issues. These are prolly on flixel, though, like buttons not centering and stuff. I'm not familiar with the demo, maybe you'll find more.

`htmlText` doesn't work when you type "help" into the console.

**Comment by larsiusprime** [comment]
Well, we might as well start a new issue for those. I'll take a look in a bit.

**Comment by Gama11** [comment]
There's input text now? Amazing! :D

**Comment by MSGhero** [comment]
Woop!
